version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-who"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "sam-hello-who"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
